services:
  - type: web
    name: backend-api
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: CHROMA_URL
        value: http://chromadb:8000
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: chromadb
    env: image
    image:
      url: docker.io/chromadb/chroma:latest
    envVars:
      - key: IS_PERSISTENT
        value: "FALSE"
